spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: postgres
    password: Anawana@19
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    validateMigrationNaming: true
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    repair-on-migrate: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: 8050
