spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: order-service

#    logging:
#      level:
#        org.springframework: DEBUG


#    kafka:
#      producer:
#        bootstrap-servers: localhost:9092
#        key-serializer: org.apache.kafka.common.serialization.StringSerializer
#        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#        properties:
#          spring.json.type.mapping: orderConfirmation:com.zikan.ecommerce.kafka.OrderConfirmation





